spring:
  application:
    name: snakymail-third-party
  cloud:
    alicloud:
      access-key: LTAI4G1Nn1uJzoshTiySyySG
      secret-key: b6FbTiUyOeiUB27nACJeCeO8B14RgC
      bucket: snakymail
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 30000

